name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: macOS-latest

    strategy:
      matrix:
        platform: [android, ios, desktop]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK for Android & Desktop builds
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ matrix.platform }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Build for Android
      - name: Build Android
        if: matrix.platform == 'android'
        run: ./gradlew assembleDebug

      # Build for iOS
      - name: Build iOS
        if: matrix.platform == 'ios'
        run: ./gradlew :shared:linkDebugFrameworkIosFat

      # Run tests
      #      - name: Run tests
      #        if: matrix.platform == 'ios'
      #        run: ./gradlew test

      # Build for Desktop
      - name: Build Desktop
        if: matrix.platform == 'desktop'
        run: ./gradlew :desktopApp:packageDistributionForCurrentOS

      # Upload artifacts
      - name: Upload Build Artifacts (Android)
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk

      - name: Upload Build Artifacts (Desktop)
        if: matrix.platform == 'desktop'
        uses: actions/upload-artifact@v4
        with:
          name: desktop-app
          path: desktopApp/build/compose/binaries/main/**/*
