name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: macOS-latest

    strategy:
      matrix:
        platform: [android, ios, desktop, tv]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK for Android & Desktop builds
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ matrix.platform }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Build Android
      - name: Build Android
        if: matrix.platform == 'android'
        run: ./gradlew :androidApp:assembleDebug

      # Build TV
      - name: Build TV
        if: matrix.platform == 'tv'
        run: ./gradlew :tvApp:assembleDebug

      # Build iOS
      - name: Build iOS
        if: matrix.platform == 'ios'
        run: ./gradlew :shared:linkDebugFrameworkIosFat

      # Build Desktop
      - name: Build Desktop
        if: matrix.platform == 'desktop'
        run: ./gradlew :desktopApp:packageDistributionForCurrentOS

      # Upload Android APK
      - name: Upload Build Artifacts (Android)
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk

      # Upload TV APK
      - name: Upload Build Artifacts (TV)
        if: matrix.platform == 'tv'
        uses: actions/upload-artifact@v4
        with:
          name: tv-apk
          path: tvApp/build/outputs/apk/debug/tvApp-debug.apk

      # Upload Desktop Artifacts
      - name: Upload Build Artifacts (Desktop)
        if: matrix.platform == 'desktop'
        uses: actions/upload-artifact@v4
        with:
          name: desktop-app
          path: desktopApp/build/compose/binaries/main/**/*

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: ${{ github.event.repository.name }} v${{ github.run_number }}

      - name: Upload Android APK to Release
        id: upload_android_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: androidApp/build/outputs/apk/debug/androidApp-debug.apk
          asset_name: androidApp-debug.apk
          asset_content_type: application/vnd.android.package-archive

  deploy:
    name: Deploy (Optional)
    needs: build
    runs-on: macOS-latest
    steps:
      - name: Deploy artifacts
        run: echo "Add your deployment steps here."
